const SITE_VERSION = '1.6.0';
const HALLOWEEN_DATE = new Date('2026-10-31T00:00:00+07:00');
const DOWNLOADS = {
  pro:{url:'https://vuotnhanh.com/dICD',filename:'Delta-Pro-v3.245.1782.apk'},
  client:{url:'https://vuotnhanh.com/j1tZ',filename:'Delta-v2.735.1138.apk'},
  D32:{url:'https://vuotnhanh.com/oJou',filename:'Delta-32bit-v2.736.1408.apk'},
  nx:{url:'https://vuotnhanh.com/TxPF',filename:'Roblox-Lite-NX-v3.0.1.apk'},
  pc:{url:'https://vuotnhanh.com/CEGE',filename:'Executor-PC-Real-v1.7.0.zip'},
  px:{url:'https://vuotnhanh.com/fXSZ',filename:'Executor-PC-Madium-v1.5.0.zip'},
  pv:{url:'https://vuotnhanh.com/zij1',filename:'Executor-PC-Velocity-v1.6.0.zip'},
  solara:{url:'https://4d38a1ec.solaraweb-alj.pages.dev/download/static/files/Bootstrapper.exe',filename:'Solara-Bootstrapper.exe'},
  xeno:{url:'https://xeno.now/',filename:'Xeno-Executor.exe'}
};
const I18N={
  vi:{subtitle:'Kho tải Executor & Client • giao diện Halloween 2026',guide:'Hướng dẫn',dark:'Tối',light:'Sáng',themeNames:{pumpkin:'Pumpkin',ghost:'Ghost',blood:'Blood Moon'},mobile:'Mobile',real:'Real',search:'Tìm executor... (Delta, Solara, Xeno...)',empty:'Không tìm thấy executor phù hợp 😢',download:'Download',calculating:'Đang tính...',favorites:'Favorites',favoriteOn:'Đã yêu thích',favoriteOff:'Thêm yêu thích',notice:'Thông báo',welcome:'Chào mừng đến NightByte 👻',noticeCopy:'Kiểm tra nguồn tải và điều khoản của nền tảng trước khi sử dụng công cụ bên thứ ba.',hideNotice:'Không hiển thị lại trong 2 giờ',guideTitle:'Hướng dẫn cài đặt & sử dụng',gotIt:'Đã hiểu ✓',faq:'Câu hỏi thường gặp',footer:'Không liên kết với Roblox Corporation.',updated:'Cập nhật',verifyTitle:'Xác nhận tải xuống',verifyIntro:'Kiểm tra tên file và nguồn tải trước khi tiếp tục.',verifyCheck:'Tôi đã kiểm tra nguồn tải và hiểu rằng đây không phải là bước quét virus.',cancel:'Hủy',continue:'Tiếp tục tải',untilHalloween:'Đến Halloween',executors:'Executors',platforms:'Platforms',favoritesStat:'Favorites',yourDevice:'Thiết bị của bạn',effects:'Hiệu ứng',effectsOff:'Hiệu ứng tắt',newUpdate:'Có bản cập nhật Halloween',updateText:`NightByte ${SITE_VERSION} đã sẵn sàng.`,guideSafety:'⚠️ Kiểm tra nguồn file trước khi mở.',installMobile:[['Tải file APK','Nhấn <b>Download</b> trên executor bạn muốn. File sẽ được lưu vào thư mục <code>Downloads</code>.'],['Cho phép cài đặt','Vào <code>Settings → Security → Install unknown apps</code> và cho phép Files hoặc Chrome cài APK.'],['Cài đặt APK','Mở file vừa tải → nhấn <b>Install</b> → chờ hoàn tất.'],['Mở Roblox','Đăng nhập Roblox và vào game bạn muốn sử dụng.'],['Mở Executor & Getkey','Mở executor → chọn <b>Getkey</b> nếu phiên bản yêu cầu key → hoàn tất xác thực.'],['Execute','Copy script → paste vào editor → nhấn <b>Execute</b>.']],installPC:[['Tải ZIP/EXE','Nhấn <b>Download</b> trên card PC. File sẽ được lưu vào <code>Downloads</code>.'],['Giải nén nếu cần','Nếu là ZIP, dùng công cụ giải nén của Windows hoặc 7-Zip.'],['Kiểm tra Windows Security','Chỉ chạy file bạn tin tưởng và kiểm tra nguồn tải trước khi mở.'],['Mở Roblox','Mở Roblox và vào game bạn muốn sử dụng.'],['Mở Executor','Khởi chạy executor PC và làm theo hướng dẫn của phiên bản đó.'],['Execute','Dán script vào editor và dùng nút <b>Execute</b> theo giao diện của executor.']],faqItems:[['Không attach/inject được?','Kiểm tra đúng phiên bản Roblox và executor, sau đó khởi động lại nếu cần.'],['Windows Security cảnh báo?','Chỉ tiếp tục khi đã kiểm tra nguồn file và hiểu rủi ro.'],['Roblox bị crash?','Cập nhật Roblox/executor và thử lại. Nếu lỗi tiếp tục, ngừng sử dụng file không tương thích.'],['Có thể bị khóa tài khoản?','Công cụ bên thứ ba có thể vi phạm điều khoản của nền tảng.']]},
  en:{subtitle:'Executor & Client downloads • Halloween 2026 interface',guide:'Guide',dark:'Dark',light:'Light',themeNames:{pumpkin:'Pumpkin',ghost:'Ghost',blood:'Blood Moon'},mobile:'Mobile',real:'Real',search:'Search executors... (Delta, Solara, Xeno...)',empty:'No matching executor found 😢',download:'Download',calculating:'Calculating...',favorites:'Favorites',favoriteOn:'Favorited',favoriteOff:'Add to favorites',notice:'Notice',welcome:'Welcome to NightByte 👻',noticeCopy:'Check the download source and platform rules before using third-party tools.',hideNotice:'Hide again for 2 hours',guideTitle:'Installation & Usage Guide',gotIt:'Got it ✓',faq:'Frequently asked questions',footer:'Not affiliated with Roblox Corporation.',updated:'Updated',verifyTitle:'Download verification',verifyIntro:'Check the filename and download source before continuing.',verifyCheck:'I checked the download source and understand this is not a virus scan.',cancel:'Cancel',continue:'Continue download',untilHalloween:'Until Halloween',executors:'Executors',platforms:'Platforms',favoritesStat:'Favorites',yourDevice:'Your device',effects:'Effects',effectsOff:'Effects off',newUpdate:'New Halloween update',updateText:`NightByte ${SITE_VERSION} is ready.`,guideSafety:'⚠️ Check the file source before opening it.',installMobile:[['Download APK','Click <b>Download</b> on the executor you want. The file will be saved to <code>Downloads</code>.'],['Allow installation','Open <code>Settings → Security → Install unknown apps</code> and allow Files or Chrome to install APKs.'],['Install the APK','Open the downloaded file → tap <b>Install</b> → wait for installation to finish.'],['Open Roblox','Sign in to Roblox and join the game you want to use.'],['Open Executor & Getkey','Open the executor → choose <b>Getkey</b> if required → complete verification.'],['Execute','Copy the script → paste it into the editor → press <b>Execute</b>.']],installPC:[['Download ZIP/EXE','Click <b>Download</b> on the PC card. The file will be saved to <code>Downloads</code>.'],['Extract if needed','If it is a ZIP, use Windows extraction or 7-Zip.'],['Check Windows Security','Only run files you trust and verify the source before opening them.'],['Open Roblox','Open Roblox and join the game you want to use.'],['Open the Executor','Launch the PC executor and follow that version’s instructions.'],['Execute','Paste the script into the editor and use <b>Execute</b> according to the executor UI.']],faqItems:[['Cannot attach/inject?','Check that Roblox and the executor versions match, then restart if needed.'],['Windows Security warning?','Continue only after checking the source and understanding the risks.'],['Roblox crashes?','Update Roblox/the executor and try again. If it continues, stop using an incompatible file.'],['Can an account be banned?','Third-party tools may violate platform terms.']]}
};
let currentLang=localStorage.getItem('language')||'vi';
let favorites=new Set(JSON.parse(localStorage.getItem('nb_favorites')||'[]'));
let favoritesOnly=false;let pendingDownload=null;let searchTimer=0;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const t=k=>I18N[currentLang][k]??k;
function toast(title,body=''){const box=$('#toastContainer');if(!box)return;const el=document.createElement('div');el.className='toast';el.innerHTML=`<strong>${title}</strong>${body?`<span>${body}</span>`:''}`;box.appendChild(el);setTimeout(()=>el.remove(),2800)}
function applyTheme(theme,save=true){document.documentElement.dataset.theme=theme;if(save)localStorage.setItem('nb_theme',theme);$('[data-role="theme-label"]').textContent=t('themeNames')[theme]||theme;$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));updateThemeMeta()}
function applyMode(mode,save=true){document.documentElement.dataset.mode=mode;if(save)localStorage.setItem('nb_mode',mode);$('#modeIcon').textContent=mode==='dark'?'☾':'☀';$('[data-role="mode-label"]').textContent=mode==='dark'?t('dark'):t('light');updateThemeMeta();if($('#systemInfo'))detectSystem()}
function updateThemeMeta(){const meta=$('meta[name="theme-color"]');if(meta)meta.content=getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()||'#09070b'}
function initThemes(){applyTheme(localStorage.getItem('nb_theme')||'pumpkin',false);applyMode(localStorage.getItem('nb_mode')||'dark',false);$('#modeToggle')?.addEventListener('click',()=>applyMode(document.documentElement.dataset.mode==='dark'?'light':'dark'));$('#themePicker')?.addEventListener('click',e=>{e.stopPropagation();$('#themeMenu').hidden=!$('#themeMenu').hidden});$$('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{applyTheme(b.dataset.themeChoice);$('#themeMenu').hidden=true;toast('Theme',t('themeNames')[b.dataset.themeChoice])}));document.addEventListener('click',e=>{if(!$('.theme-wrap')?.contains(e.target))$('#themeMenu').hidden=true})}
function applyLanguage(){document.documentElement.lang=currentLang;document.documentElement.dataset.language=currentLang;$('[data-role="lang-label"]').textContent=currentLang.toUpperCase();$('#siteSubtitle').textContent=t('subtitle');$('[data-role="guide-label"]').textContent=t('guide');$('#tab-mobile-btn .tab-text').textContent=t('mobile');$('#tab-pc-btn .tab-text').textContent=t('real');$('#searchInput').placeholder=t('search');$('#searchEmpty').textContent=t('empty');$('#guideTitle').textContent=t('guideTitle');$('#guideMobileTitle').textContent=t('mobile');$('#guidePcTitle').textContent=t('real');$('#faqLabel').textContent=t('faq');$('#guideOk').textContent=t('gotIt');$('#guideSafety').textContent=t('guideSafety');$('#noticeTitle').textContent=t('notice');$('#noticeWelcome').textContent=t('welcome');$('#noticeCopy').textContent=t('noticeCopy');$('#noticeHide').textContent=t('hideNotice');$('#footerDisclaimer').textContent=t('footer');$('#languageHint').textContent=currentLang==='vi'?'🇻🇳 Tiếng Việt • 🇬🇧 English':'🇻🇳 Vietnamese • 🇬🇧 English';$('#verifyTitle').textContent=t('verifyTitle');$('#verifyIntro').textContent=t('verifyIntro');$('#verifyCheckText').textContent=t('verifyCheck');$('#verifyCancel').textContent=t('cancel');$('#verifyConfirm').textContent=t('continue');$('[data-role="favorite-filter"]').textContent=t('favorites');$('#statExecutorsLabel').textContent=t('executors');$('#statPlatformsLabel').textContent=t('platforms');$('#statFavoritesLabel').textContent=t('favoritesStat');$('#countdownLabel').textContent=t('untilHalloween');$('#systemTitle').textContent=t('yourDevice');$('#updateTitle').textContent=t('newUpdate');$('#updateText').textContent=t('updateText');$$('.card-description').forEach(el=>el.textContent=el.dataset[currentLang]||'');renderGuide();renderFaq();updateFavoriteUI();refreshTimeAgo();applyThemesLabels()}
function applyThemesLabels(){$('[data-role="theme-label"]').textContent=t('themeNames')[document.documentElement.dataset.theme]||document.documentElement.dataset.theme;$('[data-role="mode-label"]').textContent=document.documentElement.dataset.mode==='dark'?t('dark'):t('light')}
function initLanguage(){$('#langToggle')?.addEventListener('click',()=>{currentLang=currentLang==='vi'?'en':'vi';localStorage.setItem('language',currentLang);applyLanguage()});applyLanguage()}
function renderGuide(){const make=(selector,items)=>{const list=$(selector);if(!list)return;list.innerHTML=items.map((item,i)=>`<details class="guide-step"><summary><span class="step-num">${i+1}</span><span>${item[0]}</span></summary><div class="step-body"><p>${item[1]}</p></div></details>`).join('')};make('#mobileSteps',t('installMobile'));make('#pcSteps',t('installPC'))}
function renderFaq(){const list=$('#faqList');if(!list)return;list.innerHTML=t('faqItems').map(item=>`<details class="faq-item"><summary>${item[0]}</summary><p>${item[1]}</p></details>`).join('')}
function initTabs(){$$('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{const target=btn.dataset.tab;$$('.tab-btn').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});$$('.tab-content').forEach(el=>el.classList.toggle('active',el.id===`tab-${target}`));runSearch(false) }))}
function runSearch(showEmpty=true){const query=$('#searchInput').value.trim().toLowerCase();const active=$('.tab-content.active');const cards=$$('.card',active||document);let visible=0;cards.forEach(card=>{const key=card.dataset.executor;const hay=`${card.dataset.name||''} ${card.textContent}`.toLowerCase();const show=(!query||hay.includes(query))&&(!favoritesOnly||favorites.has(key));card.hidden=!show;if(show)visible++});$('#searchClear').hidden=!query;$('#searchEmpty').hidden=!showEmpty||visible!==0}
function initSearch(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput')?.focus()}});$('#searchInput')?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>runSearch(true),70)});$('#searchClear')?.addEventListener('click',()=>{$('#searchInput').value='';$('#searchInput').focus();runSearch(false)});$('#favoriteFilter')?.addEventListener('click',()=>{favoritesOnly=!favoritesOnly;$('#favoriteFilter').classList.toggle('active',favoritesOnly);$('#favoriteFilter').firstChild.textContent=favoritesOnly?'★ ':'☆ ';runSearch(true)})}
function updateFavoriteUI(){ $$('.card').forEach(card=>{const btn=$('[data-role="favorite"]',card);if(!btn)return;const on=favorites.has(card.dataset.executor);btn.classList.toggle('active',on);btn.textContent=on?'★':'☆';btn.title=on?t('favoriteOn'):t('favoriteOff');btn.setAttribute('aria-pressed',String(on))});$('#statFavorites').textContent=String(favorites.size)}
function initFavorites(){$$('.card [data-role="favorite"]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const key=btn.closest('.card')?.dataset.executor;if(!key)return;if(favorites.has(key))favorites.delete(key);else favorites.add(key);localStorage.setItem('nb_favorites',JSON.stringify([...favorites]));updateFavoriteUI();runSearch(true);toast(favorites.has(key)?t('favoriteOn'):t('favoriteOff'),btn.closest('.card').dataset.name)}));$('#heroFavorites')?.addEventListener('click',()=>{favoritesOnly=!favoritesOnly;$('#favoriteFilter').classList.toggle('active',favoritesOnly);$('#favoriteFilter').firstChild.textContent=favoritesOnly?'★ ':'☆ ';$('#searchInput').focus();runSearch(true)})}
function initDownloadVerify(){const overlay=$('#downloadOverlay'),check=$('#verifyCheckbox'),confirm=$('#verifyConfirm');const close=()=>{overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true');check.checked=false;confirm.disabled=true;pendingDownload=null};const open=key=>{const item=DOWNLOADS[key];if(!item)return;pendingDownload=item;$('#verifyFilename').textContent=item.filename;try{$('#verifySource').textContent=new URL(item.url).hostname}catch{$('#verifySource').textContent=item.url}overlay.classList.add('show');overlay.setAttribute('aria-hidden','false');check.focus()};$$('.card [data-role="download"]').forEach(btn=>btn.addEventListener('click',()=>open(btn.closest('.card')?.dataset.executor)));check.addEventListener('change',()=>{confirm.disabled=!check.checked});confirm.addEventListener('click',()=>{if(!pendingDownload||!check.checked)return;const a=document.createElement('a');a.href=pendingDownload.url;a.target='_blank';a.rel='noopener noreferrer';a.download=pendingDownload.filename;document.body.appendChild(a);a.click();a.remove();toast('Download started',pendingDownload.filename);close()});$('#verifyClose')?.addEventListener('click',close);$('#verifyCancel')?.addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()})}
function refreshTimeAgo(){$$('.card-updated').forEach(el=>{const date=el.closest('.card')?.dataset.updated,target=$('.updated-text',el);if(!date||!target)return;const past=new Date(`${date}T00:00:00`),days=Math.max(0,Math.floor((Date.now()-past.getTime())/86400000));target.textContent=currentLang==='en'?`${t('updated')} ${days===0?'today':days===1?'1 day ago':`${days} days ago`}`:`${t('updated')} ${days===0?'hôm nay':days===1?'1 ngày trước':`${days} ngày trước`}`;el.title=past.toLocaleDateString(currentLang==='en'?'en-US':'vi-VN')})}
function updateCountdown(){const diff=Math.max(0,HALLOWEEN_DATE-Date.now());if(!diff){$('#countdown').textContent='00:00:00';return}const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;$('#countdown').textContent=d>0?`${d}d ${String(h).padStart(2,'0')}h`: `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function initCountdown(){updateCountdown();setInterval(updateCountdown,1000)}
function initParticles(){const layer=$('#particleLayer');if(!layer)return;const off=localStorage.getItem('nb_effects')==='off';if(off){document.documentElement.classList.add('effects-off');return}const chars=['🦇','✦','·','🎃'];for(let i=0;i<16;i++){const p=document.createElement('span');p.className='particle';p.textContent=chars[i%chars.length];p.style.left=`${Math.random()*100}%`;p.style.animationDuration=`${8+Math.random()*8}s`;p.style.animationDelay=`${-Math.random()*12}s`;p.style.setProperty('--drift',`${-60+Math.random()*120}px`);p.style.fontSize=`${10+Math.random()*8}px`;layer.appendChild(p)}}
function initEffects(){const btn=$('#effectsToggle');const off=localStorage.getItem('nb_effects')==='off';btn?.addEventListener('click',()=>{const now=document.documentElement.classList.toggle('effects-off');localStorage.setItem('nb_effects',now?'off':'on');if(now)$('#particleLayer').innerHTML='';else initParticles();btn.querySelector('[data-role="effects-label"]').textContent=now?t('effectsOff'):t('effects')});if(btn)btn.querySelector('[data-role="effects-label"]').textContent=off?t('effectsOff'):t('effects')}
function initUpdateNotice(){const seen=localStorage.getItem('nb_seen_version');if(seen===SITE_VERSION)return;$('#updateBanner').hidden=false;$('#updateDismiss')?.addEventListener('click',()=>{localStorage.setItem('nb_seen_version',SITE_VERSION);$('#updateBanner').hidden=true})}
function detectSystem(){const ua=navigator.userAgent;let os='Desktop';if(/Android/i.test(ua))os='Android';else if(/iPhone|iPad|iPod/i.test(ua))os='iOS';else if(/Windows/i.test(ua))os='Windows';else if(/Macintosh|Mac OS/i.test(ua))os='macOS';else if(/Linux/i.test(ua))os='Linux';let browser='Browser';if(/Edg\//i.test(ua))browser='Edge';else if(/Chrome\//i.test(ua))browser='Chrome';else if(/Firefox\//i.test(ua))browser='Firefox';else if(/Safari\//i.test(ua)&&!/Chrome\//i.test(ua))browser='Safari';const mode=document.documentElement.dataset.mode;$('#systemInfo').textContent=`${os} · ${browser} · ${mode==='dark'?'Dark':'Light'} · ${navigator.language||'en'}`}
function initGuide(){const open=()=>{$('#guideOverlay').classList.add('show');$('#guideOverlay').setAttribute('aria-hidden','false')};const close=()=>{$('#guideOverlay').classList.remove('show');$('#guideOverlay').setAttribute('aria-hidden','true')};$('#guideOpen')?.addEventListener('click',open);$('#heroGuide')?.addEventListener('click',open);$('#guideClose')?.addEventListener('click',close);$('#guideOk')?.addEventListener('click',close);$('#guideOverlay')?.addEventListener('click',e=>{if(e.target.id==='guideOverlay')close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();$('#downloadOverlay')?.classList.remove('show')}})}
function initNotice(){const overlay=$('#noticeOverlay');const hiddenUntil=Number(localStorage.getItem('nightbyte_notice_until')||0);if(Date.now()>=hiddenUntil)setTimeout(()=>{overlay.classList.add('show');overlay.setAttribute('aria-hidden','false')},450);const close=()=>{overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true')};$('#noticeClose')?.addEventListener('click',close);$('#noticeHide')?.addEventListener('click',()=>{localStorage.setItem('nightbyte_notice_until',String(Date.now()+2*60*60*1000));close()});overlay?.addEventListener('click',e=>{if(e.target===overlay)close()})}
function initLoader(){const loader=$('#loader'),bar=$('#loader-bar'),pct=$('#percentage');if(!loader)return;const start=performance.now(),duration=500;function tick(now){const p=Math.min(1,(now-start)/duration);bar.style.width=`${p*100}%`;pct.textContent=`${Math.round(p*100)}%`;if(p<1)requestAnimationFrame(tick);else loader.classList.add('hidden')}requestAnimationFrame(tick)}
function initScrollUI(){const fill=$('#readingProgressFill'),top=$('#backToTop');let ticking=false;const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(fill)fill.style.width=`${max>0?Math.min(100,scrollY/max*100):0}%`;top?.classList.toggle('show',scrollY>420);ticking=false};addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(update);ticking=true}},{passive:true});top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));update()}
addEventListener('DOMContentLoaded',()=>{initThemes();initLanguage();initLoader();initTabs();initSearch();initFavorites();initDownloadVerify();initGuide();initNotice();initCountdown();initParticles();initEffects();initUpdateNotice();detectSystem();initScrollUI();refreshTimeAgo()});
